### ISSUE TITLE
STM32F2 Support

### ISSUE THREAD

**Issue by huseyinkozan** [MaJerle/GSM-AT-commands-parser#10]
Hi,

Do you have STM32F2 support ?

**Comment by MaJerle** [comment]
Library is platform independent which means it can run on any MCU and/or PC. But drivers for STM32F2 are not implemented in this case. Only drivers for STM32F4 are as an example.

**Comment by huseyinkozan** [comment]
Thanks for the fast answer.

**Comment by MaJerle** [comment]
Currently I can only tell you that I'm working on a new version of this lib, with RTOS only support. It will feature the same concept as my latest ESP8266 library: https://github.com/MaJerle/ESP_AT_Lib

There you may expect more examples, including Visual Studio example code.

**Comment by huseyinkozan** [comment]
I am using Redbear Duo [0] with WICED SDK. Currently it builds with ThreadX. I thing, it have FreeRTOS, but did not try. I am trying to find and use an AT library with Duo.

[0] https://github.com/redbear/Duo/blob/master/docs/duo_introduction.md

**Comment by huseyinkozan** [comment]
Hi,

I thing it will be a long way to implement driver. Lots of stuff at `00-HAL_DRIVERS/STM32F4xx_HAL_Driver/`. And also I want to stay at WICED scope. I have already implemented other side with WICED.

I tried to understand 01-EXAMPLE_CLIENT_RTOS and 00-GSM_LIBRARY dirs. 
Is it possible to use `gsm_ll_template.*` and `gsm.*` files just for parsing ?

**Comment by MaJerle** [comment]
This is not really true. HAL_DRIVERS are just part of repo for examples. For STM32F2 you have already STM32F2xx_HAL_Drivers available on ST.com. You have to implement gsm_ll_template file for UART send and UART receive. Shouldn't be more than 2 hours of work.

You can use them.

**Comment by huseyinkozan** [comment]
Thanks much.

You should write `USART_RX_INTERRUPT_HANDLER_FUNCTION_NAME()` at the bottom of the file. I didn't notice it. I am trying to use it.
