### ISSUE TITLE
Stuck at GSM_Init()

### ISSUE THREAD

**Issue by huseyinkozan** [MaJerle/GSM-AT-commands-parser#11]
Hi,

I am using Telit GSM Click and stucks at `GSM_Init()`. I tried some of the AT commands manually which are given at `GSM_init()`, then got this responses:
```
AT&F
OK
AT+CMEE=1
OK
AT
OK
AT+CLCC=1
+CME ERROR: 10
AT+CPIN?
+CME ERROR: 10
AT+GMR
10.01.150
```

I have disabled call, SMS, etc at `gsm_config.h`, but `GSM_Init()` have some call related commands.
```c
#define GSM_HTTP                        0
#define GSM_FTP                         0
#define GSM_PHONEBOOK                   0
#define GSM_CALL                        0
#define GSM_SMS                         0
```

I thing you should return error code, if got any at these calls:
```c
    while (i) {
        __ACTIVE_CMD(GSM, CMD_INFO_GMR);                    /* Enable auto notification for call, +CLCC statement */
        GSM_WaitReady(GSM, 1000);
        if (GSM->ActiveResult == gsmOK) {
            break;
        }
        else { if (i < 0) return GSM->ActiveResult; }   // return at here ?
        i--;
    }
```

I will try to do these changes.

**Comment by huseyinkozan** [comment]
Do we need to enable or disable echo ? 
```c
__ACTIVE_CMD(GSM, CMD_GEN_ATE1);                    /* Disable ECHO */
```

**Comment by MaJerle** [comment]
The library itself does not support Telit modems, that's why it may not work for you.

Echo can be or enabled or not. It's purpose is debug usage.

**Comment by huseyinkozan** [comment]
Where can I find supported modems ?

**Comment by MaJerle** [comment]
If you open first page of github repository, you will see a message on top:

*Platform independent, ANSI C AT commands parser for SIMcom GSM modules*.

Only modules from SIMCom are supported. It is not easy to support all of them as there are few common commands by 3gpp standard, everything else (including most important TCPIP commands) are vendor specific and every manufacturer has litte bit different.

**Comment by huseyinkozan** [comment]
Thanks. 
Should I open pull request for my own changes ? 
Will you need them ?

**Comment by MaJerle** [comment]
This library has major architecture problems which forces me to stop any new development on it. When I will start a new lib for this device, I will for sure use the same approach as I use now in my ESP AT Lib.

**Comment by huseyinkozan** [comment]
Ok, I also have Sim800 module. And will try to use it first.
Thanks for the help. You may close this issue, if you prefer.
