### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Hmissa** [MaJerle/GSM-AT-commands-parser#2]
Hi Majerle,
I dont find the function that read the responce coming form the GSM module after the AT Command, 
the function that write in the Received variable.
Can you specify it please?
Thanks

Best Regards
Saif

**Comment by MaJerle** [comment]
There is no function which will do that automatically. You have to implement low-level layer for communicaiton (like UART on microcontroller) and then call GSM_DataReceived function with your received data.

After that, library will process it and do what it needs.

**Comment by Hmissa** [comment]
I see.
Thanks
