### ISSUE TITLE
Parse CPIN string offset not correct

### ISSUE THREAD

**Issue by GeeMing** [MaJerle/GSM-AT-commands-parser#7]
Hi Tilen,
	My device is AI-Thinker's A7 module, and I found that when request a command "**AT+CPIN?**" it
returns "**+CPIN:READY**", but in **line 1062** on file "**gsm.c**", I think the 2nd parameter should be
"**str + 6**" instead of "**str + 7**".   But maybe your device return is diffrent from mine.  I don't have
other GSM device to test currently, would you like to have a look?
	
    Regards,
    GeeMing.

**Comment by MaJerle** [comment]
SIM800 or SIM900 returns like **+CPIN: READY** with space between color na response value.
Library is for SIMcom modules. I don't know which one is AI-Thinker.
