### ISSUE TITLE
Calling is ended right after starting

### ISSUE THREAD

**Issue by suvinh** [MaJerle/GSM-AT-commands-parser#8]
Hi Tilen.

Firstly, thanks for your work on this project. It's awesome.
I'm trying testing your project with my devices, and there is a problem as the tittle.
The debugging shows:
"GSM commands parser; Compiled: Feb 10 2017 08:50:18 
 GSM Init status: 0
 Call disconnected, trying to call someone!
 Calling!
 Call finished!"
Then I used USB to UART converter to test with module SIM, it works normally.
I'm using F429 Discovery, module SIM800A, and CALL_RTOS_EXAMPLE.
Could you tell me what problem is in my case? Is it an issue? Or you just make it like this?

Thankyou very much.
Regards,
Vinh.

**Comment by MaJerle** [comment]
In my case this happened too. It was because usb can give only 500mA but sim can use up to 2A in some cases.

Increase power and try again.

**Comment by suvinh** [comment]
Yes, I used the external power.
But now it works well. Maybe because of some problem with the power.
Thankyou very much for your help.
